"""Export the merged configuration context in machine-consumable formats.

Every downstream consumer — OpenTofu/Terraform stacks, CI jobs, shell
scripts — reads the same rendered context, which is what makes ``config/``
the single source of truth rather than one input among many.
"""

from __future__ import annotations

import json
from typing import Any

import yaml

FORMATS = ("json", "yaml", "tfvars", "dotenv", "backend")


def to_json(context: dict[str, Any]) -> str:
    return json.dumps(context, indent=2, sort_keys=False) + "\n"


def to_yaml(context: dict[str, Any]) -> str:
    return yaml.safe_dump(context, sort_keys=False)


def to_tfvars(context: dict[str, Any]) -> str:
    """Terraform/OpenTofu variable file. Stacks declare a single input:

        variable "foundry_context" { type = any }
    """
    return json.dumps({"foundry_context": context}, indent=2) + "\n"


def to_dotenv(context: dict[str, Any]) -> str:
    computed = context["computed"]
    pairs = {
        "FOUNDRY_ORG": context["org"]["name"],
        "FOUNDRY_PROJECT": context["project"]["name"],
        "FOUNDRY_ENVIRONMENT": context["environment"]["name"],
        "FOUNDRY_TIER": computed["tier"],
        "FOUNDRY_PROVIDER": computed["provider"],
        "FOUNDRY_REGION": computed["region"],
        "FOUNDRY_NAME_PREFIX": computed["name_prefix"],
        "FOUNDRY_LABELS": json.dumps(computed["labels"], separators=(",", ":")),
    }
    return "".join(f"{key}={_dotenv_quote(str(value))}\n" for key, value in pairs.items())


def _dotenv_quote(value: str) -> str:
    if value == "" or any(c in value for c in ' \t"{}$'):
        return '"' + value.replace('"', '\\"') + '"'
    return value


def to_backend(context: dict[str, Any], stack: str) -> str:
    """Render a partial backend configuration (backend.hcl) from spec.state.

    Pass to init with:  tofu init -backend-config=.foundry/backend.hcl
    """
    state = context["spec"].get("state", {}) or {}
    backend = state.get("backend", "local")
    key = f"{context['computed']['state_key_prefix']}/{stack}.tfstate"

    if backend == "local":
        return "# spec.state.backend is 'local' — no remote backend config generated.\n"

    lines: list[str] = [f"# backend \"{backend}\" — generated by foundry, do not edit\n"]
    passthrough = {
        k: v
        for k, v in state.items()
        if k not in {"backend", "lock", "endpoint"} and isinstance(v, (str, int, bool)) and v != ""
    }

    if backend == "s3":
        passthrough.setdefault("bucket", "")
        lines.append(f'key = "{key}"')
        endpoint = state.get("endpoint", "")
        if endpoint:  # DigitalOcean Spaces / MinIO via the s3 backend
            lines += [
                f'endpoints = {{ s3 = "{endpoint}" }}',
                "skip_credentials_validation = true",
                "skip_requesting_account_id  = true",
                "skip_metadata_api_check     = true",
                "skip_region_validation      = true",
                "skip_s3_checksum            = true",
                "use_path_style              = true",
            ]
        if state.get("lock", True) and not endpoint:
            # Native S3 locking needs OpenTofu/Terraform >= 1.10; enable when
            # your engine floor allows it (or configure a DynamoDB table).
            lines.append("# use_lockfile = true")
    elif backend == "gcs":
        lines.append(f'prefix = "{key.removesuffix(".tfstate")}"')
    elif backend == "azurerm":
        lines.append(f'key = "{key}"')
    else:
        lines.append(f"# unknown backend '{backend}' — passing through raw settings")

    for name, value in sorted(passthrough.items()):
        rendered = json.dumps(value) if isinstance(value, (bool, int)) else f'"{value}"'
        lines.append(f"{name} = {rendered}")
    return "\n".join(lines) + "\n"


def export(context: dict[str, Any], fmt: str, stack: str = "stack") -> str:
    if fmt == "json":
        return to_json(context)
    if fmt == "yaml":
        return to_yaml(context)
    if fmt == "tfvars":
        return to_tfvars(context)
    if fmt == "dotenv":
        return to_dotenv(context)
    if fmt == "backend":
        return to_backend(context, stack)
    raise ValueError(f"unknown format '{fmt}' (choose from: {', '.join(FORMATS)})")
